[phases.setup]
nixPkgs = ["...", "jdk17"]

[phases.build]
cmds = ["mvn clean install -DskipTests"]

[phases.start]
cmd = "java -jar target/hugging-api-0.0.1-SNAPSHOT.jar"

[start]
cmd = "java -jar target/hugging-api-0.0.1-SNAPSHOT.jar"